# Generated by Django 4.2.11 on 2024-05-01 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('password', models.CharField(help_text='Use make_password to hash the password before saving.', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('height', models.IntegerField()),
                ('upper_limit', models.IntegerField()),
                ('lower_threshold', models.IntegerField()),
                ('fill_type', models.CharField(max_length=20)),
                ('subscribe_topic', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('value', models.IntegerField()),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tank.tank')),
            ],
        ),
    ]
