# Generated by Django 4.2.11 on 2024-05-02 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tank',
            name='fill_type',
        ),
        migrations.RemoveField(
            model_name='tank',
            name='subscribe_topic',
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.CreateModel(
            name='TimeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('time_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tank.tank')),
            ],
        ),
    ]
