# Generated by Django 4.2.11 on 2024-10-15 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tank', '0003_sensordata_tank_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeProfile',
        ),
    ]
