# Generated by Django 4.2.11 on 2024-10-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tank', '0004_delete_timeprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('time_start_h', models.IntegerField()),
                ('time_start_m', models.IntegerField()),
                ('time_end_h', models.IntegerField()),
                ('time_end_m', models.IntegerField()),
            ],
        ),
    ]
