# Generated by Django 4.2.11 on 2024-10-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tank', '0005_timeprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeprofile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
